## Gitignored PEMs under `tests/certs/`, generated by `tests/gen_certs.sh`.

import std/[os, osproc]

const RequiredCertFiles = [
  "ca.crt", "server.crt", "server.key", "wrong_ca.crt", "wrong_ca.key", "encrypted.key"
]

proc certDir(): string =
  currentSourcePath().parentDir / "certs"

proc certsPresent(): bool =
  let dir = certDir()
  for name in RequiredCertFiles:
    if not fileExists(dir / name):
      return false
  true

proc ensureTestCerts*(): bool =
  ## True if fixtures exist (runs openssl when missing). False only when
  ## openssl is absent and files are missing; raises on a failed generate.
  if certsPresent():
    return true
  if findExe("openssl").len == 0:
    return false
  let script = currentSourcePath().parentDir / "gen_certs.sh"
  let rc = execCmd("bash " & quoteShell(script))
  if rc != 0 or not certsPresent():
    raise newException(
      IOError,
      "failed to generate test certificates (exit " & $rc &
        "); install openssl and run `bash tests/gen_certs.sh`",
    )
  true
